name: esst/php:7.4-apache-buster

on:
  push:
    branches: main
  schedule:
    - cron: '0 1 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./php/7.4/apache-buster/Dockerfile
          tags: esst/php:7.4-apache-buster
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}