name: Build & Push Docker Images

on:
  push:
  schedule:
    - cron: '0 1 * * 1'

jobs:

  build:

    name: Build & Push Docker Images

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Wordpress - Build & Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./wordpress/Dockerfile
          tags: esst/esst:wordpress